TARGET ?= x86_64-elf
FILES=./build/start.asm.o ./build/myos.asm.o ./build/start.o ./build/stdlib.o ./build/stdio.o ./build/file.o ./build/myos.o ./build/string.o ./build/memory.o
INCLUDES=-I./src
FLAGS=-g -falign-jumps -falign-functions -falign-labels -falign-loops -fstrength-reduce -fomit-frame-pointer -finline-functions -Wno-unused-function -fno-builtin -Werror -Wno-unused-label -Wno-cpp -Wno-unused-parameter -nostdlib -nostartfiles -nodefaultlibs -Wall -O0 -Iinc

all: $(FILES)
	$(TARGET)-ld -m elf_x86_64 -relocatable $(FILES) -o ./stdlib.elf

./build/start.asm.o: ./src/start.asm
	nasm -f elf64 ./src/start.asm -o ./build/start.asm.o

./build/myos.asm.o: ./src/myos.asm
	nasm -f elf64 ./src/myos.asm -o ./build/myos.asm.o

./build/myos.o: ./src/myos.c
	$(TARGET)-gcc $(INCLUDES) $(FLAGS) -std=gnu99 -c ./src/myos.c -o ./build/myos.o

./build/start.o: ./src/start.c
	$(TARGET)-gcc $(INCLUDES) $(FLAGS) -std=gnu99 -c ./src/start.c -o ./build/start.o

./build/stdlib.o: ./src/stdlib.c
	$(TARGET)-gcc $(INCLUDES) $(FLAGS) -std=gnu99 -c ./src/stdlib.c -o ./build/stdlib.o

./build/stdio.o: ./src/stdio.c
	$(TARGET)-gcc $(INCLUDES) $(FLAGS) -std=gnu99 -c ./src/stdio.c -o ./build/stdio.o

./build/file.o: ./src/file.c
	$(TARGET)-gcc $(INCLUDES) $(FLAGS) -std=gnu99 -c ./src/file.c -o ./build/file.o

./build/string.o: ./src/string.c
	$(TARGET)-gcc $(INCLUDES) $(FLAGS) -std=gnu99 -c ./src/string.c -o ./build/string.o

./build/memory.o: ./src/memory.c
	$(TARGET)-gcc $(INCLUDES) $(FLAGS) -std=gnu99 -c ./src/memory.c -o ./build/memory.o

clean:
	rm -rf $(FILES)
	rm -rf ./stdlib.elf
