#pragma once

#define MYOS_KERNEL_LOCATION 0x100000

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define KERNEL_LONG_MODE_CODE_SELECTOR 0x18

#define KERNEL_LONG_MODE_TSS_SELECTOR 0x38

#define KERNEL_LONG_MODE_CODE_GDT_INDEX 3
#define KERNEL_LONG_MODE_DATA_GDT_INDEX 4
#define KERNEL_LONG_MODE_TSS_GDT_INDEX 7

#define TSS_DESCRIPTOR_TYPE 0x89 // Present, Ring 0, Type 9 (Available 64-bit TSS)

#define MYOS_TOTAL_INTERRUPTS 512

#define MYOS_MEMORY_MAP_TOTAL_ENTRIES_LOCATION 0x210000 // location of e820 entry count
#define MYOS_MEMORY_MAP_LOCATION 0x210008				// location of e820 entries

#define MYOS_HEAP_MINIMUM_SIZE_BYTES 104857600 // 100MB heap size
#define MYOS_HEAP_BLOCK_SIZE 4096

// Minimum address for the heap (just after 16MB mark)
// This is to avoid conflicts with the kernel and other reserved areas.
#define MYOS_MINIMAL_HEAP_ADDRESS 0x01100000

// Minimum heao table start address (just after 16MB + heap size)
#define MYOS_MINIMAL_HEAP_TABLE_ADDRESS 0x01000000

// Size of the heap table
#define MYOS_MINIMAL_HEAP_TABLE_SIZE MYOS_MINIMAL_HEAP_ADDRESS - MYOS_MINIMAL_HEAP_TABLE_ADDRESS

#define MYOS_SECTOR_SIZE 512

#define MYOS_MAX_FILESYSTEMS 12
#define MYOS_MAX_FILE_DESCRIPTORS 512

#define MYOS_MAX_PATH 108

#define MYOS_TOTAL_GDT_SEGMENTS 6

#define MYOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define MYOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define MYOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3ff000
#define MYOS_PROGRAM_VIRTUAL_ADDRESS_END MYOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - MYOS_USER_PROGRAM_STACK_SIZE

#define MYOS_MAX_PROGRAM_ALLOCATIONS 1024
#define MYOS_MAX_PROCESSES 12

#define USER_DATA_SEGMENT 0x33
#define USER_CODE_SEGMENT 0x2b

#define MYOS_MAX_ISR80H_COMMANDS 1024

#define MYOS_KEYBOARD_BUFFER_SIZE 1024
